[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc = "0.8.26"
optimizer = true
optimizer_runs = 10_000
via_ir = false
evm_version = "cancun"
remappings = [
    "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/",
    "forge-std/=lib/forge-std/src/",
]

[profile.default.fuzz]
runs = 256
max_test_rejects = 65536

[profile.ci]
fuzz = { runs = 1000 }

[rpc_endpoints]
monad = "https://rpc.monad.xyz"

[etherscan]
monad = { key = "${ETHERSCAN_API_KEY}", url = "https://api.etherscan.io/v2/api?chainid=143", chain = 143 }

[fmt]
bracket_spacing = false
int_types = "long"
line_length = 120
multiline_func_header = "all_params"
number_underscore = "thousands"
quote_style = "double"
tab_width = 4
wrap_comments = true
